---
- name: add vhost
  template: src=apache_api_vhost.j2 dest=/etc/apache2/sites-available/api.{{ webserver_hostname }}.conf
  sudo: true
  notify:
    - restart apache2

- name: enable the apache_api_vhost site
  command: a2ensite api.{{ webserver_hostname }}.conf creates=/etc/apache2/sites-enabled/api.{{ webserver_hostname }}.conf
  sudo: true
  when: ansible_os_family == "Debian"
  notify:
    - restart apache2
