---
- name: add vhost
  template: src=apache_poly_vhost.j2 dest=/etc/apache2/sites-available/poly.{{ webserver_hostname }}.conf
  sudo: true
  notify:
    - restart apache2

- name: enable the apache_poly_vhost site
  command: a2ensite poly.{{ webserver_hostname }}.conf creates=/etc/apache2/sites-enabled/poly.{{ webserver_hostname }}.conf
  sudo: true
  when: ansible_os_family == "Debian"
  notify:
    - restart apache2
